In [1]:
import numpy as np

In [5]:
array = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
array

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
array.shape

(9,)

In [9]:
array_modificada = array.reshape(3, 3)
array_modificada

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [17]:
array_modificada = array.reshape(-1, 3)
array_modificada

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
array_reversa = array_modificada.transpose()
array_reversa

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [21]:
# METODO FLATTEN()   METODO RAVEL()

In [25]:
array_copia = array.flatten()
array_copia

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
array_visual = array.ravel()
array_visual

array([1, 2, 3, 4, 5, 6, 7, 8, 9])