In [1]:
import numpy as np

In [3]:
array1d = np.array([1, 2, 3, 4, 5])

In [5]:
array2d = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

In [11]:
array1d[2]

3

In [15]:
array2d[0][-1]

3

In [17]:
array1d[1:4]

array([2, 3, 4])

In [31]:
array2d[2,:2]

array([7, 8])

In [39]:
array2d[:,1:2]

array([[2],
       [5],
       [8]])

In [42]:
array1d > 3

array([False, False, False,  True,  True])

In [44]:
array2d % 2 == 0

array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])