In [21]:
import numpy as np

In [3]:
x = [1, 2, 3]
y = [1, 2, 3]
z = [1, 2, 3]

In [5]:
np.concatenate([x,y,z])

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [51]:
a = np.array([[1, 2],
              [3, 4]])
b = np.array([[5, 6],
              [7, 8]])
resultado = np.concatenate([a,b], axis=1)
print(resultado)

[[1 2 5 6]
 [3 4 7 8]]


In [47]:
array_concatenado = np.concatenate([a, b], axis=0)
array_concatenado

array([[1, 2],
       [3, 4],
       [5, 6],
       [7, 8]])

In [49]:
array_concatenado.shape

(4, 2)

In [53]:
array_reformar = array_concatenado.reshape(2, 4)
array_reformar

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [55]:
array_reformar.shape

(2, 4)

In [57]:
array_sumatoria = array_reformar + array_reformar
array_sumatoria

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16]])

In [59]:
array_multi = array_reformar * array_reformar
array_multi

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [61]:
raiz = np.sqrt(array_multi)
raiz

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])