In [1]:
import numpy as np

In [5]:
array1 = np.array([1, 2, 3])
array2 = np.array([[0],[10],[20],[30]])

In [7]:
array1

array([1, 2, 3])

In [9]:
array2

array([[ 0],
       [10],
       [20],
       [30]])

In [11]:
# BROADCAST OPERACION

In [15]:
sumatoria = array2 + array1
sumatoria

array([[ 1,  2,  3],
       [11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [19]:
multiplicacion = array2 * array1
multiplicacion

array([[ 0,  0,  0],
       [10, 20, 30],
       [20, 40, 60],
       [30, 60, 90]])

In [21]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

In [25]:
resultado = np.add(a, b)
resultado

array([5, 7, 9])

In [29]:
resultado_log = np.log(a)
resultado_log

array([0.        , 0.69314718, 1.09861229])

In [31]:
resultado_log_base = np.log10(b)
resultado_log_base

array([0.60205999, 0.69897   , 0.77815125])

In [33]:
raiz = np.sqrt(a)
raiz

array([1.        , 1.41421356, 1.73205081])

In [37]:
multiplar = np.multiply(a, b)
multiplar

array([ 4, 10, 18])