In [1]:
import numpy as np

In [48]:
array = np.array([1, 2, np.nan, 4, 5])
array

array([ 1.,  2., nan,  4.,  5.])

In [60]:
np.isnan(array)

array([False, False,  True, False, False])

In [52]:
np.mean(array)

nan

In [54]:
np.nanmean(array)

3.0

In [56]:
array_nan_sus = np.where(np.isnan(array), 0, array)
array_nan_sus

array([1., 2., 0., 4., 5.])

In [58]:
nuevo_promedio = np.nanmean(array)
array_promedio_sus = np.where(np.isnan(array), nuevo_promedio, array)
array_promedio_sus

array([1., 2., 3., 4., 5.])

In [62]:
array_del = array[np.isnan(array)]
array_del

array([nan])

In [64]:
array_del = array[~np.isnan(array)]
array_del

array([1., 2., 4., 5.])